<?php


namespace app\adminapi\controller;


use tools\jwt\Token;
use think\Controller;
use think\Request;

class BaseApi extends Controller
{
    //无需进行登录检测的请求
    protected $no_login=['login/login','login/captcha'];

    /**
     *
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //处理跨域预检请求
        //允许的源域名
        header("Access-Control-Allow-Origin: *");
        //允许的请求头信息
        header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization");
        //允许的请求类型
        header('Access-Control-Allow-Methods: GET, POST, PUT,DELETE,OPTIONS,PATCH');
//        try{
//            //验证非法请求
//            $request=Request::instance();
//            //获取当前请求的控制器名称
//            $controller=$request->controller();
//            //获取当前请求的方法名称
//            $action=$request->action();
//            if (!in_array($controller.'/'.$action,$this->no_login)){
//                //将客户端传递的token值获取 并还原出user_id
//                $user_id=Token::getUserId();
//                if (empty($user_id)){
//                    $this->fail("请登录后重试！");
//                }
//            }
//
//        }catch (\Exception $e){
//            $this->fail("操作异常，请查询后再试",403);
//        }

    }

    /**
     * 通用响应
     * @param int $code 错误码
     * @param string $msg 错误描述
     * @param array $data 返回数据
     */
    public function response($code = 200, $msg = 'success', $data = [])
    {
        $res = [
            'code' => $code,
            'msg' => $msg,
            'data' => $data
        ];
        //以下两行二选一
        //echo json_encode($res, JSON_UNESCAPED_UNICODE);die;
        json($res)->send();
        die;
    }

    /**
     * 失败时响应
     * @param string $msg 错误描述
     * @param int $code 错误码
     */
    public function fail($msg = 'fail', $code = 500)
    {
        return $this->response($code, $msg);
    }

    /**
     * 成功时响应
     * @param array $data 返回数据
     * @param int $code 错误码
     * @param string $msg 错误描述
     */
    public function ok($data = [], $code = 200, $msg = 'success')
    {
        return $this->response($code, $msg, $data);
    }
}